# -*- coding: utf-8 -*-
"""game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zBSxPC7Sw5L8x-Ouw2DWBplvK_SKVga_
"""

import streamlit as st
import random
from random import choice

st.title('Rock Paper Scissor Game')

a=['Rock','Paper','Scissor']
com_choice=choice(a)

if st.button("Rock"):
  if com_choice=='Rock':
    st.write('User and Computer has choosen the same Choice, PLay Again ')
  if com_choice=='Paper':
    st.write('Computer has Choosen Paper. Computer Wins !!! ')
  if com_choice=='Scissor':
    st.write('Computer has choosen Scissor. User Wins !!!')

if st.button("Paper"):
  if com_choice=='Rock':
    st.write('Computer has choosen Rock, User Wins !!! ')
  if com_choice=='Paper':
    st.write('User and Computer has choosen same Choice, Play Again ')
  if com_choice=='Scissor':
    st.write('Computer has Choosen Scissor, Computer Wins !!! ')

if st.button("Scissor"):
  if com_choice=='Rock':
    st.write('Computer has Choosen Rock, Computer Wins !!! ')
  if com_choice=='Paper':
    st.write('Computer has Choosen Paper. User Wins !!! ')
  if com_choice=='Scissor':
    st.write('User and Computer has choosen same Choice, Play Again ')